config/routes.rb
Rails.application.routes.draw do
 

  resources :zadania_glownes

  resources :wiadomoscis

  get 'student/za1'# =>'student#za1'
  get 'student/za2'# =>'student#za2'
  get 'student/za3'# =>'student#za3'
  get 'student/za4'# =>'student#za4'
  get 'student/za5'# =>'student#za5'
  get 'student/panel' =>'student#panel'
  
  post 'student/rozwiazanie'# => 'student#rozwiazanie'
  
  get 'student/challenge'# =>'student#challenge'
  get 'student/chosechallenge'# =>'student#chosechallenge'
  get 'student/challengeodp' #=>'student#challengeodp'
  get 'student/challengeodp2'# =>'student#challengeodp2'
  get 'student/challengeinbox'# =>'student#challengeinbox'
  post 'student/challengeconfirm'# =>'student#challengeconfirm'
  post 'student/challengeconfirm2'# =>'student#challengeconfirm2'
  
  get 'konto/rejestracja'

  get 'logowanie_form' => 'konto#logowanie_form'
  
  post 'logowanie' => 'konto#logowanie'
  
  delete 'logout' => 'konto#wylogowanie'

  get 'konto/pierwsze_logowanie'

  root 'database#index'
  
  resources :wykladowca do
    resources :zadania_glownes
    resources :grupies, shallow: true do
      resources :student
    end
  end
   
  
   
  

end

app/models/zadania_glowne.rb
class ZadaniaGlowne < ActiveRecord::Base
  belongs_to :wykladowca
end

app/controllers/zadania_glownes_controller.rb
class ZadaniaGlownesController < ApplicationController
  before_action :set_zadania_glowne, only: [:show, :edit, :update, :destroy]

  # GET /zadania_glownes
  # GET /zadania_glownes.json
  def index
    @zadania_glownes = ZadaniaGlowne.all
    if zalogowany_student? #todo adam
    end 
  end

  # GET /zadania_glownes/1
  # GET /zadania_glownes/1.json
  def show
  end

  # GET /zadania_glownes/new
  def new
    @zadania_glowne = ZadaniaGlowne.new
  end

  # GET /zadania_glownes/1/edit
  def edit
  end

  # POST /zadania_glownes
  # POST /zadania_glownes.json
  def create
    @zadania_glowne = ZadaniaGlowne.new(zadania_glowne_params)

    respond_to do |format|
      if @zadania_glowne.save
        format.html { redirect_to @zadania_glowne, notice: 'Zadania glowne was successfully created.' }
        format.json { render :show, status: :created, location: @zadania_glowne }
      else
        format.html { render :new }
        format.json { render json: @zadania_glowne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zadania_glownes/1
  # PATCH/PUT /zadania_glownes/1.json
  def update
    respond_to do |format|
      if @zadania_glowne.update(zadania_glowne_params)
        format.html { redirect_to @zadania_glowne, notice: 'Zadania glowne was successfully updated.' }
        format.json { render :show, status: :ok, location: @zadania_glowne }
      else
        format.html { render :edit }
        format.json { render json: @zadania_glowne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zadania_glownes/1
  # DELETE /zadania_glownes/1.json
  def destroy
    @zadania_glowne.destroy
    respond_to do |format|
      format.html { redirect_to zadania_glownes_url, notice: 'Zadania glowne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zadania_glowne
      @zadania_glowne = ZadaniaGlowne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zadania_glowne_params
      params.require(:zadania_glowne).permit(:poziom_zadania,:nr_zadania,:pkt_za_zadanie,:tresc,:podpowiedz)
    end
end

app/helpers/zadania_glownes_helper.rb
module ZadaniaGlownesHelper
end

app/views/zadania_glownes/_form.html.erb
<%= form_for(@zadania_glowne) do |f| %>
  <% if @zadania_glowne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zadania_glowne.errors.count, "error") %> prohibited this zadania_glowne from being saved:</h2>

      <ul>
      <% @zadania_glowne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
  <%=f.label :poziom_zadania%>
  <%=f.text_field :poziom_zadania%>
</div>
    <div class="field">
  <%=f.label :nr_zadania%>
  <%=f.text_field :nr_zadania%>
</div>
    <div class="field">
  <%=f.label :pkt_za_zadanie%>
  <%=f.text_field :pkt_za_zadanie%>
</div>
    <div class="field">
  <%=f.label :tresc%>
  <%=f.text_field :tresc%>
</div>
    <div class="field">
  <%=f.label :podpowiedz%>
  <%=f.text_field :podpowiedz%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/zadania_glownes/edit.html.erb
<h1>Editing Zadania Glowne</h1>

<%= render 'form' %>

<%= link_to 'Show', @zadania_glowne %> |
<%= link_to 'Back', zadania_glownes_path %>

app/views/zadania_glownes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zadania Glownes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zadania_glownes.each do |zadania_glowne| %>
      <tr>
        <td><%= zadania_glowne.poziom_zadania%></td>
        <td><%= zadania_glowne.nr_zadania%></td>
        <td><%= zadania_glowne.pkt_za_zadanie%></td>
        <td><%= zadania_glowne.tresc%></td>
        <td><%= zadania_glowne.podpowiedz%></td>
        <td><%= link_to 'Show', zadania_glowne %></td>
        <td><%= link_to 'Edit', edit_zadania_glowne_path(zadania_glowne) %></td>
        <td><%= link_to 'Destroy', zadania_glowne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zadania glowne', new_zadania_glowne_path %>

app/views/zadania_glownes/new.html.erb
<h1>New Zadania Glowne</h1>

<%= render 'form' %>

<%= link_to 'Back', zadania_glownes_path %>

app/views/zadania_glownes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_zadania_glowne_path(@zadania_glowne) %> |
<%= link_to 'Back', zadania_glownes_path %>