config/routes.rb
Rails.application.routes.draw do
 

  resources :zadania_glownes

  resources :wiadomoscis

  get 'student/za1'# =>'student#za1'
  get 'student/za2'# =>'student#za2'
  get 'student/za3'# =>'student#za3'
  get 'student/za4'# =>'student#za4'
  get 'student/za5'# =>'student#za5'
  get 'student/panel' =>'student#panel'
  
  post 'student/rozwiazanie'# => 'student#rozwiazanie'
  
  get 'student/challenge'# =>'student#challenge'
  get 'student/chosechallenge'# =>'student#chosechallenge'
  get 'student/challengeodp' #=>'student#challengeodp'
  get 'student/challengeodp2'# =>'student#challengeodp2'
  get 'student/challengeinbox'# =>'student#challengeinbox'
  post 'student/challengeconfirm'# =>'student#challengeconfirm'
  post 'student/challengeconfirm2'# =>'student#challengeconfirm2'
  
  get 'konto/rejestracja'

  get 'logowanie_form' => 'konto#logowanie_form'
  
  post 'logowanie' => 'konto#logowanie'
  
  delete 'logout' => 'konto#wylogowanie'

  get 'konto/pierwsze_logowanie'

  root 'database#index'
  
  resources :wykladowca do
    resources :zadania_glownes
    resources :grupies, shallow: true do
      resources :student
    end
  end
   
  
   
  

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :grupy , class_name: "Grupy"
  has_one :wykladowca, :through => :grupy

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    before_action :aktywny_student, only: :show
  
      
  def new
    grupy = Grupy.find(params[:grupy_id])
    @students = grupy.students.build
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @students }
    end
  end
  
  def create
    grupy = Grupy.find(params[:grupy_id])
    @students = grupy.students.create(student_params_wykladowca)
    @students.login = params[:student][:nralbumu]
    @students.haslo = params[:student][:nralbumu]
    respond_to do |format|
      if @students.save
        format.html { redirect_to :back, notice: 'Grupy was successfully created.' }
        format.json { render :show, status: :created, location: @students }
      else
        format.html { render :action => "new" }
        format.json { render json: @students.errors, status: :unprocessable_entity }
      end
    end
    student = Student.find_by(nralbumu: params[:student][:nralbumu] )
    progres = Progre.new(student_id: student.id, pkt_rankingowe: "0", zdrowie: "100", doswiadczenie: "0", level: 1)
    progres.save
  end
  

  
    def show
        @student = Student.find_by(login: session[:login])
        @progr=Progre.find_by(student_id: session[:user_id])

        @zad=WylosowaneZadanium.find_by(student_id: session[:user_id])
        if @zad.nil?
         @gr=Grupy.find_by(id: @student.grupy_id)
         for j in 1..5 do
          for i in 1..5 do
            #zadania na dzien1
            
            wszystkiezadania=ZadaniaGlowne.where(wykladowca_id: @gr.wykladowca_id, poziom_zadania: j , nr_zadania: i).count
            los11= session[:user_id] % wszystkiezadania
            if los11==0
                los11=1
            end
            zad=ZadaniaGlowne.where(wykladowca_id: @gr.wykladowca_id, poziom_zadania: j , nr_zadania: i).first(los11).last
            data={
                "student_id"=>session[:user_id],
                "poziom"=>j,
                "numer"=>i,
                "zadania_glowne_id"=>zad.id
            }
            @zad=WylosowaneZadanium.new(data)
            @zad.save
          end
         end
        end
       gr= Student.find(session[:user_id])
       progresy=Progre.order(pkt_rankingowe: :desc)
        i=1
        k=0
       progresy.each do |pr|
       k=k+1
            if pr.student_id==session[:user_id]
                @ran=i
                @j=k
            end
            gru=Student.find(pr.student_id)
            if gru.grupy_id==gr.grupy_id
                i=i+1
            end
       end
    end
    
    def aktywny_student
       redirect_to root_url if zalogowany_student.nil?
    end 
    
    def rozwiazanie
        @zad=Rozwiazanium.find_by(student_id: session[:user_id])
        idzadania=WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: params[:zad][:poziom_zadania], numer: params[:zad][:nr_zadania])
        tre=ZadaniaGlowne.find_by(id: idzadania.zadania_glowne_id)
        @zad.update_attributes(:odpowiedz => params[:zad][:odp], :tresc_zadania =>  tre.tresc, :punkty => params[:zad][:punkty])
        if @zad.save
           redirect_to :back
        end
    end

    def challengeinbox
        @wyzwania=ZadaniaPoboczne.where(wyzwany: session[:user_id])
    end
    
    
    def edit
        @student = find_student
    end
    
    def update
      @student = find_student
      if zalogowany_student?
        @student.nr_logowania = true
        respond_to do |format|
         if @student.update(student_param)
            format.html { redirect_to @student, notice: 'Student was successfully updated.' }
            format.json { render :show, status: :ok, location: @student }
         else
            format.html { render :action => "edit" }
            format.json { render json: @student.errors, status: :unprocessable_entity }
         end
        end
      end
      if zalogowany_wykladowca?
        respond_to do |format|
          if @student.update(student_params_wykladowca)
            format.html { redirect_to @student, notice: 'Student was successfully updated.' }
            format.json { render :show, status: :ok, location: @grupy }
          else
            format.html { render :action => "edit" }
            format.json { render json: @student.errors, status: :unprocessable_entity }
          end
        end
      end
    end
    
    def destroy
        @student = Student.find(params[:id])
        @student.destroy
        respond_to do |format|
            format.html { redirect_to :back, notice: 'Student was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    
    def challenge
        student=Student.find(session[:user_id])
        @idgru=Student.where(grupy_id: student.grupy_id)
    end
    
    def chosechallenge
        poziom=Progre.find_by(student_id: session[:user_id])
        @zadania=ZadaniaGlowne.where(poziom_zadania: poziom.level)   
        @wyzwany=Student.find(params[:idst])
    end
    
    def challengeconfirm
         student=Student.find(session[:user_id])
        grupa=Grupy.find_by(student.grupy_id)
        zadanie=ZadaniaGlowne.find(params[:zad][:zadanie])
        data={
            "wykladowca_id" => grupa.wykladowca_id ,
            "poziom_zadania" => zadanie.poziom_zadania ,
            "zadanie_tresc" => zadanie.tresc ,
            "wyzywajacy" => session[:user_id],
            "odpowiedz_wyzywajacego" => params[:zad][:odp],
            "wyzwany" => params[:zad][:wyzwany],
            "odpowiedz_wyzwanego" => "",
            "status" => "0"
        }
        ZadaniaPoboczne.new(data).save
        redirect_to root_url
    end
    
    def challengeconfirm2
        wyzwanie=ZadaniaPoboczne.find(params[:zad][:wyzwanie])
        wyzwanie.update_attributes(:odpowiedz_wyzwanego => params[:zad][:odp] , :status=>1)
        if wyzwanie.save
            redirect_to root_url
        end
    end
    
    private
    
    def aktywny_student
       redirect_to root_url if zalogowany_student.nil?
    end
    def student_params_wykladowca
        params.require(:student).permit(:nralbumu)
    end
    def student_param
      params.require(:student).permit(:login,:haslo,:email,:imie,:nazwisko)
    end
    
    def find_student
        Student.find(params[:id])
    end
 
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/_panel.html.erb
<%
@student = Student.find_by(login: session[:login])
@progr=Progre.find_by(student_id: session[:user_id])

gr= Student.find(session[:user_id])
       progresy=Progre.order(pkt_rankingowe: :desc)
        i=1
        k=0
       progresy.each do |pr|
       k=k+1
            if pr.student_id==session[:user_id]
                @ran=i
                @j=k
            end
            gru=Student.find(pr.student_id)
            if gru.grupy_id==gr.grupy_id
                i=i+1
            end
       end
%>

<h1>zalogowano do kąta <%= @student.imie%></h1>
Imię i nazwisko: <%= @student.imie %> <%= @student.nazwisko %><br></br>
level <%=@progr.level %><br></br>
zdrowie <%=@progr.zdrowie %><br></br>
doswiadczenie <%=@progr.doswiadczenie %><br></br>
punkty rankingowe <%=@progr.pkt_rankingowe %><br></br>
pozycja w rankingu grupy <%= @ran %><br></br>
pozycja w rankingu światowym <%= @j %><br></br>
<br>|<%= link_to "Mapa świata", student_path(session[:user_id]) %> |
<%= link_to "Wiadomosci", wiadomoscis_path(session[:user_id]) %><%= Wiadomosci.where(student_id: session[:user_id], przeczytana: "0").count%> |
<%= link_to "Edytuj profil", edit_student_path(session[:user_id]) %> |
<%= link_to "challenge", student_challenge_path(session[:user_id]) %> |
<%= link_to "challenge otrzymane", student_challengeinbox_path(session[:user_id]) %><%= ZadaniaPoboczne.where(wyzwany: session[:user_id], status: "0").count%> |
</br>
<br>---------------------------------------------------------------------------------------------------------------</br>

app/views/student/challenge.html.erb
<%= render "panel" %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% i=0%>
  <tbody>
    <% @idgru.each do |stud| %>
      <tr>
        <td><%= i=1+i %></td>
        <td><%= stud.imie %></td>
        <td><%= stud.nazwisko %></td>
        <td><%= link_to "wybierz zadanie", student_chosechallenge_path(:idst => stud.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/student/challengeinbox.html.erb
<%= render "panel" %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% i=0%>
  <tbody>
    <% @wyzwania.each do |wyzwanie| %>
      <tr>
          <% if wyzwanie.status==0 %>
            <td><%= i=1+i %></td>
            <td><%= Student.find(wyzwanie.wyzywajacy).imie %></td>
            <td><%= Student.find(wyzwanie.wyzywajacy).nazwisko %></td>
            <td><%= link_to "Rozwiaż", student_challengeodp2_path(:idwyzwania => wyzwanie.id)%></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/student/challengeodp.html.erb
<%= render "panel" %>
<%= link_to "Mapa świata", student_path(session[:user_id]) %>
<br><%=ZadaniaGlowne.find_by(id: params[:zada]).tresc%></br>
<%= form_for :zad, url: {action: "challengeconfirm"} do |f| %>
  <%= f.hidden_field "zadanie", :value => params[:zada] %>
  <%= f.hidden_field "wyzwany", :value => params[:idst] %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %> 

app/views/student/challengeodp2.html.erb
<%= render "panel" %>
<br><%=ZadaniaPoboczne.find(params[:idwyzwania]).zadanie_tresc%></br>
<%= form_for :zad, url: {action: "challengeconfirm2"} do |f| %>
  <%= f.hidden_field "wyzwanie", :value => params[:idwyzwania] %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %> 

app/views/student/chosechallenge.html.erb
<%= render "panel" %>
<%= link_to "Mapa świata", student_path(session[:user_id]) %>
<br>Wyzywasz <%= @wyzwany.imie %> <%= @wyzwany.nazwisko %> na pojedynek</br>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% i=0%>
  <tbody>
    <% @zadania.each do |zad| %>
      <tr>
        <td><%= i=1+i %></td>
        <td><%= zad.tresc %></td>
        <td><%= link_to "sprawdz go", student_challengeodp_path(:idst => @wyzwany.id, :zada => zad.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/student/edit.html.erb
<% if zalogowany_wykladowca? %>
<h1>Editing Student</h1>

<%= form_for @student do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this grupy from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
  <%=f.label :nralbumu %>
  <%=f.text_field :nralbumu%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show',  @student %> |
<%= link_to 'Back', grupy_path(@student.grupy_id) %>
<%else%>
  <%= form_for @student do |f| %>
    <div class="field">
  <%=f.label :login %>
  <%=f.text_field :login%>
</div>
<div class="field">
  <%=f.label :haslo %>
  <%=f.text_field :haslo%>
</div>
<div class="field">
  <%=f.label :email %>
  <%=f.text_field :email %>
</div>
<div class="field">
  <%=f.label :imie %>
  <%=f.text_field :imie %>
</div>
<div class="field">
  <%=f.label :nazwisko %>
  <%=f.text_field :nazwisko%>
</div>


  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
<%end%>

app/views/student/new.html.erb
<%= form_for ([@students.grupy, @students]), url: {action: "create"} do |f| %>
  <% if @students.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@students.errors.count, "error") %> prohibited this grupy from being saved:</h2>

      <ul>
      <% @students.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%=f.label :nralbumu %>
  <%=f.text_field :nralbumu%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', grupy_path(params[:grupy_id]) %>

app/views/student/za2.html.erb
<%= link_to "Mapa świata", student_path(session[:user_id]) %>
<br></br>
<br>Zadanie 1</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "1").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
  <%= f.hidden_field "poziom_zadania", :value => 2 %>
  <%= f.hidden_field "nr_zadania", :value => 1 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 2</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "2").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 2 %>
  <%= f.hidden_field "nr_zadania", :value => 2 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 3</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "3").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 2 %>
  <%= f.hidden_field "nr_zadania", :value => 3 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 4</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "4").zadania_glowne_id).tresc%></br>
<%= render "panel" %>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 2 %>
  <%= f.hidden_field "nr_zadania", :value => 4 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 5</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "5").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 2 %>
  <%= f.hidden_field "nr_zadania", :value => 5 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>

app/views/student/za3.html.erb
<%= link_to "Mapa świata", student_path(session[:user_id]) %>
<br></br>
<br>Zadanie 1</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "1").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
  <%= f.hidden_field "poziom_zadania", :value => 3 %>
  <%= f.hidden_field "nr_zadania", :value => 1 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 2</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "2").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 3 %>
  <%= f.hidden_field "nr_zadania", :value => 2 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 3</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "3").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 3 %>
  <%= f.hidden_field "nr_zadania", :value => 3 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<%= render "panel" %>
<% end %>
<br></br>
<br>Zadanie 4</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "4").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 3 %>
  <%= f.hidden_field "nr_zadania", :value => 4 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 5</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "5").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 3 %>
  <%= f.hidden_field "nr_zadania", :value => 5 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>

app/views/student/za4.html.erb
<%= link_to "Mapa świata", student_path(session[:user_id]) %>
<br></br>
<br>Zadanie 1</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "1").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
  <%= f.hidden_field "poziom_zadania", :value => 4 %>
  <%= f.hidden_field "nr_zadania", :value => 1 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 2</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "2").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 4 %>
  <%= f.hidden_field "nr_zadania", :value => 2 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 3</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "3").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 4 %>
  <%= f.hidden_field "nr_zadania", :value => 3 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 4</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "4").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= render "panel" %>
 <%= f.hidden_field "poziom_zadania", :value => 4 %>
  <%= f.hidden_field "nr_zadania", :value => 4 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 5</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "5").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 4 %>
  <%= f.hidden_field "nr_zadania", :value => 5 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>

app/views/student/za5.html.erb
<%= link_to "Mapa świata", student_path(session[:user_id]) %>
<br></br>
<br>Zadanie 1</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "1").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
  <%= f.hidden_field "poziom_zadania", :value => 5 %>
  <%= f.hidden_field "nr_zadania", :value => 1 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 2</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "2").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 5 %>
  <%= f.hidden_field "nr_zadania", :value => 2 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 3</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "3").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= render "panel" %>
 <%= f.hidden_field "poziom_zadania", :value => 5 %>
  <%= f.hidden_field "nr_zadania", :value => 3 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 4</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "4").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 5 %>
  <%= f.hidden_field "nr_zadania", :value => 4 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>
<br></br>
<br>Zadanie 5</br>
<br><%=ZadaniaGlowne.find_by(id: WylosowaneZadanium.find_by(student_id: session[:user_id], poziom: "2", numer: "5").zadania_glowne_id).tresc%></br>
<%= form_for :zad, url: {action: "rozwiazanie"} do |f| %>
 <%= f.hidden_field "poziom_zadania", :value => 5 %>
  <%= f.hidden_field "nr_zadania", :value => 5 %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %>