config/routes.rb
Rails.application.routes.draw do
 

  resources :zadania_glownes

  resources :wiadomoscis

  get 'student/za1'# =>'student#za1'
  get 'student/za2'# =>'student#za2'
  get 'student/za3'# =>'student#za3'
  get 'student/za4'# =>'student#za4'
  get 'student/za5'# =>'student#za5'
  get 'student/panel' =>'student#panel'
  
  post 'student/rozwiazanie'# => 'student#rozwiazanie'
  
  get 'student/challenge'# =>'student#challenge'
  get 'student/chosechallenge'# =>'student#chosechallenge'
  get 'student/challengeodp' #=>'student#challengeodp'
  get 'student/challengeodp2'# =>'student#challengeodp2'
  get 'student/challengeinbox'# =>'student#challengeinbox'
  post 'student/challengeconfirm'# =>'student#challengeconfirm'
  post 'student/challengeconfirm2'# =>'student#challengeconfirm2'
  
  get 'konto/rejestracja'

  get 'logowanie_form' => 'konto#logowanie_form'
  
  post 'logowanie' => 'konto#logowanie'
  
  delete 'logout' => 'konto#wylogowanie'

  get 'konto/pierwsze_logowanie'

  root 'database#index'
  
  resources :wykladowca do
    resources :zadania_glownes
    resources :grupies, shallow: true do
      resources :student
    end
  end
   
  
   
  

end

app/models/wiadomosci.rb
class Wiadomosci < ActiveRecord::Base
  belongs_to :wykladowca
  belongs_to :student
end

app/controllers/wiadomoscis_controller.rb
class WiadomoscisController < ApplicationController
  before_action :set_wiadomosci, only: [:show, :edit, :update, :destroy]


  # GET /wiadomoscis
  # GET /wiadomoscis.json
  def index
    if zalogowany_student?
        @wiadomoscis = Wiadomosci.where(student_id: session[:user_id], przeczytana: "0")
    end
    if zalogowany_wykladowca?
      @wiadomoscis = Wiadomosci.where(wykladowca_id: session[:user_id], przeczytana: "1")
    end

  end

  # GET /wiadomoscis/1
  # GET /wiadomoscis/1.json
  def show
  end

  # GET /wiadomoscis/new
  def new
    @wiadomosci = Wiadomosci.new
  end

  # GET /wiadomoscis/1/edit
  def edit
  end

  # POST /wiadomoscis
  # POST /wiadomoscis.json
  def create
   if zalogowany_student?
    createstu
   end
   if zalogowany_wykladowca?
    createwy
   end
  end
  def createstu
    student=Student.find_by(id: session[:user_id])
    gr=Grupy.find_by(student.grupy_id)
    @wiadomosci = Wiadomosci.new(wiadomosci_params)
    @wiadomosci.student_id=session[:user_id]
    @wiadomosci.wykladowca_id=gr.wykladowca_id
    @wiadomosci.przeczytana="1"

      respond_to do |format|
        if @wiadomosci.save

          format.html { redirect_to @wiadomosci, notice: 'Wiadomosci was successfully created.' }
          format.json { render :show, status: :created, location: @wiadomosci }
        else
          format.html { render :new }
          format.json { render json: @wiadomosci.errors, status: :unprocessable_entity }
        end
      end
  end
    def createwy
      @wiadomosci = Wiadomosci.new(wiadomosci_params)
      @wiadomosci.wykladowca_id=session[:user_id]
       @wiadomosci.student_id=params[:wiadomosci][:id]
      @wiadomosci.przeczytana="0"

        respond_to do |format|
          if @wiadomosci.save
            format.html { redirect_to @wiadomosci, notice: 'Wiadomosci was successfully created.' }
            format.json { render :show, status: :created, location: @wiadomosci }
          else
            format.html { render :new }
            format.json { render json: @wiadomosci.errors, status: :unprocessable_entity }
          end
        end
    end



  # PATCH/PUT /wiadomoscis/1
  # PATCH/PUT /wiadomoscis/1.json
  def update
    respond_to do |format|
      if @wiadomosci.update(wiadomosci_params)
        format.html { redirect_to @wiadomosci, notice: 'Wiadomosci was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiadomosci }
      else
        format.html { render :edit }
        format.json { render json: @wiadomosci.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiadomoscis/1
  # DELETE /wiadomoscis/1.json
  def destroy
    @wiadomosci.destroy
    respond_to do |format|
      format.html { redirect_to wiadomoscis_url, notice: 'Wiadomosci was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiadomosci
      @wiadomosci = Wiadomosci.find(session[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiadomosci_params
      params.require(:wiadomosci).permit(:temat, :tresc)
    end


end

app/helpers/wiadomoscis_helper.rb
module WiadomoscisHelper
end

app/views/wiadomoscis/_form.html.erb
<%= render "student/panel" %>

<%= form_for(@wiadomosci) do |f| %>
  <% if @wiadomosci.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiadomosci.errors.count, "error") %> prohibited this wiadomosci from being saved:</h2>

      <ul>
      <% @wiadomosci.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label "temat" %><br>
  <%= f.text_field "temat" %><br>
  <%= f.label "tresc" %><br>
  <%= f.text_area :tresc, size: "60x5" %><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wiadomoscis/_form1.html..erb
<%= form_for(@wiadomosci) do |f| %>
  <% if @wiadomosci.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiadomosci.errors.count, "error") %> prohibited this wiadomosci from being saved:</h2>

      <ul>
      <% @wiadomosci.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label "numer albumu studenta" %><br>
  <%= f.text_field "nralbumu" %><br>
  <%= f.label "temat" %><br>
  <%= f.text_field "temat" %><br>
  <%= f.label "tresc" %><br>
  <%= f.text_area :tresc, size: "60x5" %><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wiadomoscis/_form1.html.erb
<%= form_for(@wiadomosci) do |f| %>
  <% if @wiadomosci.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiadomosci.errors.count, "error") %> prohibited this wiadomosci from being saved:</h2>

      <ul>
      <% @wiadomosci.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field "id", :value => params[:iid] %>
  <%= f.label "temat" %><br>
  <%= f.text_field "temat" %><br>
  <%= f.label "tresc" %><br>
  <%= f.text_area :tresc, size: "60x5" %><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wiadomoscis/edit.html.erb
<h1>Editing Wiadomosci</h1>

<%= render 'form' %>

<%= link_to 'Show', @wiadomosci %> |
<%= link_to 'Back', wiadomoscis_path %>

app/views/wiadomoscis/index.html.erb
<% if zalogowany_student? %>
    <%= render "student/panel" %>
<%end%>
<p id="notice"><%= notice %></p>

<h1>Wiadomosci</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% i=0%>
  <tbody>
    <% @wiadomoscis.each do |wiadomosci| %>
      <tr>
        <td><%= i=1+i %></td>
        <td><%= wiadomosci.temat %></td>
        <td><%= link_to 'Otworz', wiadomosci_path(:id => wiadomosci.id) %></td>
        <td><%= link_to 'Usuń', wiadomosci, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if zalogowany_student? %>
  <br><%= link_to 'zadaj pytanie wykladowcy', new_wiadomosci_path(:id => session[:user_id])%></br>
<% end  %>
<br></br>
<%= link_to 'Back', student_path(session[:user_id]) %>

app/views/wiadomoscis/new.html.erb
<h1>New Wiadomosci</h1>
<% if zalogowany_student? %>
    <%= render 'form' %>
<%end %>
<% if zalogowany_wykladowca? %>
    <%= render 'form1' %>
<%end %>

<%= link_to 'Back', wiadomoscis_path %>

app/views/wiadomoscis/show.html.erb
<% if zalogowany_student? %>
    <%= render "student/panel" %>
    <br><%= link_to "Powrót do skrzynki odbiorczej", wiadomoscis_path(session[:user_id]) %>
<%end%>
<p id="notice"><%= notice %></p>

<br>temat: <%= Wiadomosci.find(params[:id]).temat %></br>
    tresc: <%= Wiadomosci.find(params[:id]).tresc %>

<% if zalogowany_student? %>
    <br>
        <%= link_to 'Odpowiedz', new_wiadomosci_path(session[:user_id])%>
   </br>
<% else %>
    <br>
         <%= link_to 'Odpowiedz', new_wiadomosci_path(session[:user_id])%>
    </br>
<% end %>

<br></br>
<%= link_to 'Back', wiadomoscis_path %>