config/routes.rb
Rails.application.routes.draw do
 

  resources :zadania_glownes

  resources :wiadomoscis

  get 'student/za1'# =>'student#za1'
  get 'student/za2'# =>'student#za2'
  get 'student/za3'# =>'student#za3'
  get 'student/za4'# =>'student#za4'
  get 'student/za5'# =>'student#za5'
  get 'student/panel' =>'student#panel'
  
  post 'student/rozwiazanie'# => 'student#rozwiazanie'
  
  get 'student/challenge'# =>'student#challenge'
  get 'student/chosechallenge'# =>'student#chosechallenge'
  get 'student/challengeodp' #=>'student#challengeodp'
  get 'student/challengeodp2'# =>'student#challengeodp2'
  get 'student/challengeinbox'# =>'student#challengeinbox'
  post 'student/challengeconfirm'# =>'student#challengeconfirm'
  post 'student/challengeconfirm2'# =>'student#challengeconfirm2'
  
  get 'konto/rejestracja'

  get 'logowanie_form' => 'konto#logowanie_form'
  
  post 'logowanie' => 'konto#logowanie'
  
  delete 'logout' => 'konto#wylogowanie'

  get 'konto/pierwsze_logowanie'

  root 'database#index'
  
  resources :wykladowca do
    resources :zadania_glownes
    resources :grupies, shallow: true do
      resources :student
    end
  end
   
  
   
  

end

app/models/grupy.rb
class Grupy < ActiveRecord::Base
  belongs_to :wykladowca, class_name: "Wykladowca"
  has_many :students, class_name: "Student"
  
end

app/controllers/grupies_controller.rb
class GrupiesController < ApplicationController

  # GET /grupies
  # GET /grupies.json
  def index
    @grupies = Grupy.where("wykladowca_id = :wykladowca_id", wykladowca_id: params[:wykladowca_id])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @grupies }
    end
  end

  # GET /grupies/1
  # GET /grupies/1.json
  def show
    @grupy = Grupy.find(params[:id])
    @students = Student.where("grupy_id = :grupy_id", grupy_id: @grupy.id)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @grupy }
    end
  end


  # GET /grupies/new
  def new
    wykladowca = Wykladowca.find(params[:wykladowca_id])
    @grupy = wykladowca.grupies.build
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @grupy }
    end
  end

  # GET /grupies/1/edit
  def edit
    @grupy = Grupy.find(params[:id])
  end

  # POST /grupies
  # POST /grupies.json
  def create
    wykladowca = Wykladowca.find(params[:wykladowca_id])
    @grupy = wykladowca.grupies.create(grupy_params)
    respond_to do |format|
      if @grupy.save
        format.html { redirect_to @grupy, notice: 'Grupy was successfully created.' }
        format.json { render :show, status: :created, location: @grupy }
      else
        format.html { render :action => "new" }
        format.json { render json: @grupy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupies/1
  # PATCH/PUT /grupies/1.json
  def update
    @grupy = Grupy.find(params[:id])
    respond_to do |format|
      if @grupy.update(grupy_params)
        format.html { redirect_to @grupy, notice: 'Grupy was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupy }
      else
        format.html { render :action => "edit" }
        format.json { render json: @grupy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupies/1
  # DELETE /grupies/1.json
  def destroy
    @grupy = Grupy.find(params[:id])
    @grupy.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Grupy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupy_params
      params.require(:grupy).permit(:nazwa)
    end
end

app/helpers/grupies_helper.rb
module GrupiesHelper
end

app/views/grupies/_form.html.erb
<%= form_for ([@grupy.wykladowca, @grupy]) do |f| %>
  <% if @grupy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupy.errors.count, "error") %> prohibited this grupy from being saved:</h2>

      <ul>
      <% @grupy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%=f.label :nazwa%>
  <%=f.text_field :nazwa%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grupies/_students.html.erb
<h1>Lista Studentów</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.login%></td>
        <td><%= student.haslo%></td>
        <td><%= student.nralbumu%></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student)%></td>
        <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>
        <td><%= link_to 'napisz', new_wiadomosci_path(:iid => student.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj Studenta', new_grupy_student_path(params[:id]) %>

app/views/grupies/edit.html.erb
<h1>Editing Grupy</h1>

<%= form_for @grupy do |f| %>
  <% if @grupy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupy.errors.count, "error") %> prohibited this grupy from being saved:</h2>

      <ul>
      <% @grupy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%=f.label :nazwa%>
  <%=f.text_field :nazwa%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show',  @grupy %> |
<%= link_to 'Back', wykladowca_grupies_path(@grupy.wykladowca) %>

app/views/grupies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grupies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupies.each do |grupy| %>
      <tr>
        <td><%= grupy.nazwa%></td>
        <td><%= link_to 'Show', grupy %></td>
        <td><%= link_to 'Edit', edit_grupy_path(grupy)%></td>
        <td><%= link_to 'Destroy', grupy, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupy', new_wykladowca_grupy_path %>

app/views/grupies/new.html.erb
<h1>New Grupy</h1>

<%= render 'form' %>

<%= link_to 'Back', wykladowca_grupies_path(@grupy.wykladowca) %>

app/views/grupies/show.html.erb
<%= render 'students'%>
<%= link_to 'Edit', edit_grupy_path(@grupy) %> |
<%= link_to 'Back', wykladowca_grupies_path(@grupy.wykladowca) %>